.gitignore, android.py, bcl.py, cmd_utils.py, desktop.py, llvm.py, options.py, wasm.py
I haven't thoroughly tested yet but it seems to work for `python3 ./linux.py make --target=x86_64 --jobs 7`.
=> Add option to specify make build jobs (--jobs)

android.py, bcl.py, cmd_utils.py, desktop.py, ios.py, llvm.py, options.py, reference_assemblies.py, wasm.py
Follow-up to #4.
Scripts can now be called with `--jobs` without argument, which will
pass `-j` to `make` and trigger its behavior:
> If the -j option is given without an argument, make will not
> limit the number of jobs that can run simultaneously.
=> Improve --jobs command to support no argument (max jobs)

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature---enhancement-request.md, .github/workflows/static_checks.yml, format.sh
The formatting script is `format.sh`, and the file which causes it to be ran automatically on GitHub Actions is
`.github/workflows/ci.yml`. The metadata mentioned in the title includes issue templates and funding information.
The CI check does run because this repo already has other CI checks.
=> Add a formatting script for GitHub Actions and add GitHub metadata

android.py
This allows using the script on a system without Python 2 installed.
(`make_standalone_toolchain.py` uses `/usr/bin/env python` as shebang.)
Note that as of NDK r19 and later (i.e. anything we'd support now), `make_standalone_toolchain.py` is deprecated and we should look into using the new system: https://developer.android.com/ndk/guides/other_build_systems
=> Android: Force using python3 for `make_standalone_toolchain.py`

.github/workflows/build.yml, files/patches/mono_ios_asl_log_deprecated.diff, format.sh, ios.py, llvm.py, patch_emscripten.py
This is what we'll be using for official builds for 3.2.4+.
---
This is an attempt to see if that could fix the Wasm builds. The current failure seems to be due to Mono's buildsystem not being ready yet in 6.8 to use the new `EMSDK` env variable instead of relying on the existence of `~/.emscripten`.
=> CI: Build with Mono 6.12.0.111 and Emscripten 1.39.7

README.md, bcl.py, desktop.py
This PR is intended to make it easier to build Godot with a patched mono build (see https://github.com/godotengine/godot/pull/42039).
The main feature is a new 'copy_bcl' action for the desktop.py script, but I have also added section to the README to document the process.
=> Make it a little easier to get a successful working build

files/patches/wasn_m2n_trampolines_hook.diff
Mono on WASM relies on trampolines for a fixed pre-defined set of method signatures in order for the interpreter to call native functions.
As a workaround for this limitation, Godot has been passing `long`, `ulong`, `float` and `double` as pointers in internal calls.
This patch should allow Godot to provide its own trampolines, which can be generated automatically at compile time thanks to templates.
This patch is made against the Mono tag `mono-6.12.0.111`. The following commit is expected to break this patch:
mono/mono@174aeaa31c9d80a53c6c7981ba7206825cd1ea4d
It will need to be updated once we upgrade the a newer Mono version in the official Godot builds.
=> WASM: Add patch to let Godot provide its own m2n trampolines

android.py
Fixes https://github.com/godotengine/godot/issues/44159.
*Note:* I have yet to test an actual build with the change, it could be that Mono outright doesn't support API level < 21. I'll rebuild my container and report back.
*Update:* I rebuilt my container successfully, now using it to make a test Android+Mono build of 3.2.4-beta3.
=> Android: Fix support for API 18-20 for 32-bit

.github/workflows/build.yml, README.md
Following up on #22, we should target API level 18 like the Godot source does,
which is used by armv7/x86 builds. 64-bit builds do require API level 21 as a
minimum, but our build scripts handle upgrading this value already.
I upgraded my build containers to use Mono 6.12.0.114 (latest Preview), and also bumped Android CMake version to 3.10.2.4988404 which is what we use in official builds (shouldn't matter much).
=> CI: Bump Mono to 6.12.0.114 and fix Android 32-bit min API

desktop.py
Seems like https://github.com/godotengine/godot/issues/50486 was not due to cross-compilation issues, but to the fact that `windows.py copy_bcl` didn't properly copy the `desktop-win32` BCL, so we were using the `desktop` (POSIX) one.
That's why @bruvzg found that projects exported to Windows with 3.4 beta 1 worked fine, since the export workflow properly uses the `net_4_x-win32` BCL.
---
Got a successful container build (will PR in a bit), currently testing the produced builds to validate.
=> bcl: Fix copy_bcl for desktop-win32 profile

README.md, bcl.py, desktop.py
Fixes https://github.com/godotengine/godot/issues/36958 by enabling BTLS when building Mono for Windows. `--enable-dynamic-btls` was changed to `--enable-btls` in `desktop.py` because https://github.com/mono/mono/pull/3829 appears to have made it so that they're the same. I also corrected what I expect was a typo.
Note: I haven't actually tested this as I don't own a Linux or OSX computer.
=> Enable BTLS when building for Windows

files/patches/fix-mono-log-spam.diff, patch_mono.py
Port of https://github.com/mono/mono/pull/20980, which itself is based on https://github.com/Unity-Technologies/mono/commit/37dc7aae643fa1d86f183044379352eac074d96e. Applies cleanly on the latest `2020-02` branch.
This prevents Mono logs from being spammed, which could result in log file sizes in the dozens of gigabytes.
```
❯ ./patch_mono.py --mono-sources mono                              
Running: patch -N -p1 < /home/hugo/Documents/Git/godotengine/godot-mono-builds/files/patches/fix-mono-android-tkill.diff
patching file mono/metadata/threads.c
Hunk #1 succeeded at 78 (offset 1 line).
patching file mono/utils/mono-threads-posix.c
Hunk #1 succeeded at 32 (offset 1 line).
Running: patch -N -p1 < /home/hugo/Documents/Git/godotengine/godot-mono-builds/files/patches/fix-mono-log-spam.diff …
```
=> Fix Mono log spam

desktop.py, files/patches/btls-cmake-args-linux-mingw.diff, patch_mono.py
Patched Mono to make the BTLS CMake build work with MinGW on Linux.
This includes @akien-mga's patch for `mono/btls/CMakeLists.txt` to make it build with `-static-libgcc`.
=> Windows: Configure with `--enable-btls-lib` to build BTLS dll

.github/workflows/build.yml, README.md, android.py
Following https://github.com/godotengine/godot/pull/51719.
Also removes now obsolete code to check whether we're using NDK 18+,
since we don't support any earlier version.
=> Android: Bump min SDK to 19, target SDK to 30

.github/workflows/build.yml, README.md
Should also fix CI by including
https://github.com/mono/mono/commit/5a21247f3669777823babd1c75bc199c32aa7484
For the record I've been using 6.12.0.158 for several months for official builds. I don't know why I never PR'ed it here.
=> Mono: Bump to 6.12.0.174

desktop.py
Follow-up to #47 and #49.
This caused issues on macOS ARM64, see https://github.com/godotengine/build-containers/issues/95.
Supersedes #64.
=> desktop: Only enable btls-lib on Windows

.github/workflows/build.yml, README.md, android.py, options.py
Upgrades Android NDK to the current supported LTS version: r23c.
Closes #68.
There have been some significant changes over the years. Most importantly, there is no longer a need to build independent architecture based toolchains or build platform cross-compilers.
This PR includes the following additional changes:
- I've moved the selection and default NDK version, the minimum Android API, and the CMake version from the Github workflow to the `android.py` build script. So anyone building these for themselves will have the same experience.
- I've removed the installation of the Android SDK from the workflow build. As per the [documentation](https://github.com/actions/virtual-environments/blob/ubuntu20/20220626.1/images/linux/Ubuntu2004-Readme.md#android), the Ubuntu 20.20 build environment …
=> Upgrade Android NDK to r23 LTS

.github/workflows/build.yml
Here are github-action runs on my fork:
- [Static checks action](https://github.com/Atlinx/godot-mono-builds/actions/runs/3120741803)
- [Build action](https://github.com/Atlinx/godot-mono-builds/actions/runs/3120737874)
=> Add arm64 to osx build

.github/workflows/build.yml
[ci skip]
Tested successfully on my fork:
https://github.com/akien-mga/godot-mono-builds/tree/release-943cc86
I'll merge this manually together with other PRs to get a single CI build and save on CI resources for @godotengine.
=> Fix Android artifact names after #69

.github/workflows/build.yml
Should help alleviate this kind of issue when compiling Godot itself with our Linux SDK and trying to use prebuilt Mono:
```
ld: /home/runner/mono-installs/desktop-linux-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-mono-rand.o): in function `mono_rand_try_get_bytes':
(.text+0x16a): undefined reference to `getrandom'
```
---
I didn't like my first patch modifying `desktop.py` to change the hardcoded triple for Linux, so instead I tweaked the Linux SDK setup script to create `x86_64-linux-gnu-*` symlinks for the existing `x86_64-godot-linux-gnu-*` triples of our Linux SDK.
We can see later on with @hpvb if the Linux SDK should include those symlinks from the start for compatibility.
=> CI: Use our own Linux SDK to maximize glibc compatibilty
